### ISSUE TITLE
ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY  Broken lockfile

### ISSUE THREAD

**Issue by ittipatken** [docchula/el-player#8]
https://github.com/pnpm/pnpm/issues/6609#issuecomment-1569324563

I believe that this is a `pnpm` bug. Upgrading to `pnpm@8.6.0` or reverting back to `lockfileVersion: '6.0'`  should fix this.

**Comment by ittipatken** [comment]
This was fixed on [pnpm 8.6.2](https://github.com/pnpm/pnpm/releases/tag/v8.6.2).

**Comment by keenthekeen** [comment]
Upgrading pnpm on the sever to v8.6.2 doesn't solve the problem.

**Comment by keenthekeen** [comment]
Seems fixed by the combination of:
- upgrading pnpm on the server to v8.6.2
- upgrading actions/checkout to v3 in GitHub Actions config (https://github.com/docchula/el-player/commit/8a5906697a5c278fba819a278be6c773187fb4c3)
- running `pnpm update` (https://github.com/docchula/el-player/commit/e06a5022c49803d10a2d0cc2b1112def7caccdc1)
